### ISSUE TITLE
Support MADLAD-400 - multilingual machine translation model based on the T5 architecture

### ISSUE THREAD

**Issue by carolinaxxxxx** [OpenNMT/CTranslate2#1560] opened 2023-11-20 16:17 UTC
Hi Team,

please consider adding support for models from the collection: https://huggingface.co/collections/jbochi/madlad-400-65491e6a78726cac9a4b84b7

Short description:

MADLAD-400 is a multilingual machine translation model based on the T5 architecture that was trained on 250 billion tokens covering over 450 languages using publicly available data. It is competitive with models that are significantly larger.

Paper: https://huggingface.co/papers/2309.04662

Thank you very much for your work. Best regards 👍 🥇

**Comment by vince62s** [comment] 2023-11-21 09:44
I think @Ehsan-Jahanbakhsh converted it using the T5 template, how did it go ?

**Comment by Ehsan-Jahanbakhsh** [comment] 2023-11-21 12:42
it works well. the huggingface model ([link](https://huggingface.co/jbochi/madlad400-3b-mt/tree/main) had a broken tokenizer that has been fixed.
`ct2-transformers-converter` works now. (although in order to convert correctly #1552 is needed)

**Comment by vince62s** [comment] 2023-11-21 13:28
Closing then, will be fine for next release.

**Closed by vince62s** 2023-11-21 13:28 UTC
Labels: enhancement

**Comment by carolinaxxxxx** [comment] 2023-11-22 23:22
@Ehsan-Jahanbakhsh How to use MADLAD-400 with ctranslate2?

I converted the model, use with:

```
import ctranslate2
import transformers

translator = ctranslate2.Translator("/path/to/model", device="cuda", compute_type="float16")
tokenizer = transformers.AutoTokenizer.from_pretrained("jbochi/madlad400-7b-mt")

input_text = "<2de> The house is wonderful."
input_tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(input_text))

results = translator.translate_batch([input_tokens])

output_tokens = results[0].hypotheses[0]
output_text = tokenizer.decode(tokenizer.convert_tokens_to_ids(output_tokens))

print(output_text
```

Result:

`<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>`

**Comment by Ehsan-Jahanbakhsh** [comment] 2023-11-22 23:32
See [This](https://forum.opennmt.net/t/ctranslate2-supports-madlad-400/5564)

**Comment by carolinaxxxxx** [comment] 2023-11-23 00:11
@Ehsan-Jahanbakhsh

> See [This](https://forum.opennmt.net/t/ctranslate2-supports-madlad-400/5564). Do you have the same problem with 3b version?

Same here.

Conversion:

`ct2-transformers-converter --model jbochi/madlad400-3b-mt --quantization float16`

Test code:

```
import ctranslate2
import transformers

translator = ctranslate2.Translator("/path/to/model", device="cuda", compute_type="float16")
tokenizer = transformers.AutoTokenizer.from_pretrained("jbochi/madlad400-3b-mt")

input_text = "<2de> The house is wonderful."
input_tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(input_text))

results = translator.translate_batch([input_tokens])

output_tokens = results[0].hypotheses[0]
output_text = tokenizer.decode(tokenizer.convert_tokens_to_ids(output_tokens))

print(output_text
```

Result:

`<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>`

**Comment by Ehsan-Jahanbakhsh** [comment] 2023-11-23 10:12
I was not able to reproduce this results. please run the inference on CPU with float32 or int8 and see if the problem persists.

**Comment by carolinaxxxxx** [comment] 2023-11-23 18:39
@Ehsan-Jahanbakhsh int8 CPU is ok, result:

`Das Haus ist wunderbar. `

Do you have any idea what might be causing it? Maybe something with the conversion? Can you share the models you converted?

THx ✌️

**Comment by Ehsan-Jahanbakhsh** [comment] 2023-11-23 18:41
I don't have the means, but it would be cool if someone tested float32 on a gpu.

**Comment by carolinaxxxxx** [comment] 2023-11-23 18:48
@Ehsan-Jahanbakhsh float32 on GPU is ok, result:

`Das Haus ist wunderbar.`

So I guess there is something wrong with the float16 conversion.

**Comment by vince62s** [comment] 2023-11-23 20:16
it's a known issue with T5 models. Google it you will find discussions on this.

**Comment by carolinaxxxxx** [comment] 2023-11-23 20:17
Ok. He'll look around.. Thx.

**Comment by vince62s** [comment] 2023-11-23 20:21
https://github.com/OpenNMT/CTranslate2/issues/1074

**Comment by carolinaxxxxx** [comment] 2023-11-24 00:06
@vince62s thanks for that ✌️
