### ISSUE TITLE
8-bit translation raises error CUBLAS_STATUS_NOT_SUPPORTED on T4 GPU 

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/CTranslate2#829] opened 2022-06-09 07:34 UTC
I also have this problem. When I quantify it to float16, I do not report an error, but when I quantify it to int8, I will report the following errors.

![image](https://user-images.githubusercontent.com/10346684/172790072-bfd146b9-f893-49e6-9dc4-93c5289377a0.png)

_Originally posted by @Andrewlesson in https://github.com/OpenNMT/CTranslate2/issues/414#issuecomment-1150775130_

**Comment by guillaumekln** [comment] 2022-06-09 08:04
I just tried to run 8-bit translation on a T4 GPU and could not reproduce any error with the latest version 2.19.0.

Can you describe your environment (CUDA version, driver version) and the steps to reproduce the error?

**Comment by Andrewlesson** [comment] 2022-06-09 08:19
> I just tried to run 8-bit translation on a T4 GPU and could not reproduce any error with the latest version 2.19.0.
> 
> Can you describe your environment (CUDA version, driver version, etc.) and the steps to reproduce the error?

![image](https://user-images.githubusercontent.com/10346684/172799490-c93337ee-b7b6-4f04-90bd-9e1f5d2f737e.png)

**Comment by guillaumekln** [comment] 2022-06-09 08:40
In your first screenshot we can't see the full `translate_batch` line. Can you post the full code snippet?

Can you also run your code in verbose mode (`CT2_VERBOSE=1 python ...`) and report the output?

**Comment by Andrewlesson** [comment] 2022-06-09 08:48
> In your first screenshot we can't see the full `translate_batch` line. Can you post the full code snippet?
> 
> Can you also run your code in verbose mode (`CT2_VERBOSE=1 python3 ...`) and report the output?


![image](https://user-images.githubusercontent.com/10346684/172804754-fce61736-54ff-4792-8309-62c964259777.png)

**Comment by guillaumekln** [comment] 2022-06-16 12:24
> This is the complete error log after using verbose mode

This does not look like the complete log as there are no logs coming from CTranslate2 (there should be lines with `[ctranslate2]`).

Can you try running the model directly (instead of the OpenNMT-py server) and copy-paste the full console output? Also please avoid screenshots which are harder to read.

**Comment by guillaumekln** [comment] 2022-07-04 08:54
Let me close this issue as I'm not able to reproduce the error on T4 GPUs with the provided information.

Feel free to reopen if you have more information to share. Currently it looks like an issue with CUDA installation. You can try running the code in a CUDA Docker container to ensure a proper environment.

**Closed by guillaumekln** 2022-07-04 08:54 UTC
