### ISSUE TITLE
Converted Vicuna-7b-v1.5-16k and longdoes not seem to generate sensible output

### ISSUE THREAD

**Issue by chiiyeh** [OpenNMT/CTranslate2#1404] opened 2023-08-04 12:42 UTC
I converted [vicuna-7b-v1.5](https://huggingface.co/lmsys/vicuna-7b-v1.5),  [vicuna-7b-v1.5-16k](https://huggingface.co/lmsys/vicuna-7b-v1.5-16k) and  [longchat-7b-v1.5-32k](https://huggingface.co/lmsys/longchat-7b-v1.5-32k) without any issue. 

However when running through the prompt
```
prompt = (
    "Girafatron is obsessed with giraffes, the most glorious animal on the face of this Earth. "
    "Giraftron believes all other animals are irrelevant when compared to the glorious majesty "
    "of the giraffe.\nDaniel: Hello, Girafatron!\nGirafatron:"
)
tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(prompt))
results = generator.generate_batch([tokens], sampling_topk=10, max_length=200, include_prompt_in_result=False)
output = tokenizer.decode(results[0].sequences_ids[0])
```
Both the vicuna-7b-v1.5-16k and longchat-7b-v1.5-32k did not generate any sensible output despite a few tries.

Did not manage to run the pytorch version of both the model so not too sure if it is model issue or something else.

**Comment by guillaumekln** [comment] 2023-08-04 12:45
Duplicate of #1403.

**Closed by guillaumekln** 2023-08-04 12:45 UTC
