### ISSUE TITLE
WHISPER: Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/CTranslate2#1315] opened 2023-06-23 12:42 UTC
Hi,
 I'm trying to run a Whisper model with  the [script](https://opennmt.net/CTranslate2/guides/transformers.html#whisper) I found in the docs on GPU. However I get this error when `generate()` is called:

`Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory`

Do I need CUDA 12?

I've just made the following chage in the script:
` model = ctranslate2.models.Whisper(sys.argv[1], device="cuda")`

**Comment by guillaumekln** [comment] 2023-06-23 13:05
Hi,

How did you install CTranslate2?

It looks like you compiled the library from the source since the released binaries use CUDA 11, not CUDA 12.

**Comment by anderleich** [comment] 2023-06-23 13:14
With pip:

`pip install ctranslate2`

**Comment by guillaumekln** [comment] 2023-06-23 13:27
First, reinstall CTranslate2 to make sure you get the version from PyPI and not somewhere else:

```
pip install --force-reinstall ctranslate2
```

Please post the installation output in this issue.

Then can you also post the output of the following command:

```
ldconfig -p | grep cublas
```

**Comment by anderleich** [comment] 2023-06-23 13:52
This is the installation output:
```
Collecting ctranslate2
  Using cached ctranslate2-3.16.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
Collecting numpy (from ctranslate2)
  Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting pyyaml<7,>=5.3 (from ctranslate2)
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Installing collected packages: pyyaml, numpy, ctranslate2
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0
    Uninstalling PyYAML-6.0:
      Successfully uninstalled PyYAML-6.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.3
    Uninstalling numpy-1.24.3:
      Successfully uninstalled numpy-1.24.3
  Attempting uninstall: ctranslate2
    Found existing installation: ctranslate2 3.16.0
    Uninstalling ctranslate2-3.16.0:
      Successfully uninstalled ctranslate2-3.16.0
Successfully installed ctranslate2-3.16.0 numpy-1.24.3 pyyaml-6.0
```
And this, the output of ldconfig:

```
	libcublasLt.so.11 (libc6,x86-64) => /usr/local/cuda-11/targets/x86_64-linux/lib/libcublasLt.so.11
	libcublasLt.so.11 (libc6,x86-64) => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublasLt.so.11
	libcublasLt.so (libc6,x86-64) => /usr/local/cuda-11/targets/x86_64-linux/lib/libcublasLt.so
	libcublasLt.so (libc6,x86-64) => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublasLt.so
	libcublas.so.11 (libc6,x86-64) => /usr/local/cuda-11/targets/x86_64-linux/lib/libcublas.so.11
	libcublas.so.11 (libc6,x86-64) => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublas.so.11
	libcublas.so.10.0 (libc6,x86-64) => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublas.so.10.0
	libcublas.so (libc6,x86-64) => /usr/local/cuda-11/targets/x86_64-linux/lib/libcublas.so
	libcublas.so (libc6,x86-64) => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublas.so

```

**Comment by guillaumekln** [comment] 2023-06-23 13:58
You probably installed cuDNN for CUDA 12, but you should install cuDNN for CUDA 11 instead.

**Comment by guillaumekln** [comment] 2023-06-23 14:02
How did you install cuDNN?

**Comment by anderleich** [comment] 2023-06-23 14:20
```
pip install nvidia-pyindex
pip install nvidia-cudnn
```

**Comment by guillaumekln** [comment] 2023-06-23 14:27
The cuDNN version installed with pip is not automatically recognized by CTranslate2 unless you set `LD_LIBRARY_PATH`. Did you set `LD_LIBRARY_PATH`? If not it means you have another cuDNN installation somewhere else. Can you check that?

```
ldconfig -p | grep cudnn
```

**Comment by anderleich** [comment] 2023-06-23 14:35
It seems there are other installations:

```
	libcudnn_ops_train.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8
	libcudnn_ops_train.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so
	libcudnn_ops_infer.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
	libcudnn_ops_infer.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so
	libcudnn_cnn_train.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8
	libcudnn_cnn_train.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so
	libcudnn_cnn_infer.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8
	libcudnn_cnn_infer.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so
	libcudnn_adv_train.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8
	libcudnn_adv_train.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so
	libcudnn_adv_infer.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8
	libcudnn_adv_infer.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so
	libcudnn.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.8
	libcudnn.so.7 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.7
	libcudnn.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so

```

**Comment by guillaumekln** [comment] 2023-06-23 14:48
Yes that's probably the issue. I think one of these cuDNN installation is for CUDA 12 and not CUDA 11. You can check for a reference to `libcublasLt.so.12` in the ldd output, for example:

```
ldd /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8
```

**Comment by anderleich** [comment] 2023-06-23 14:58
I couldn't find any references to `libcublasLt.so.12`. It seems cuDNN v8 is installed

**Comment by luckymomohd** [comment] 2023-07-15 19:42
I have the exact same problem.
CTranslate2 was installed via `pip install ctranslate2` on WSL2 with Ubuntu-20.04.

Running faster-whisper in any way gives me this error:
`Could not load library libcublas.so.12. Error: libcublas.so.12: cannot open shared object file: No such file or directory`

Even running CTranslate2 compiled by me still gives me the same error.

I checked all CUDA & cuDNN installations and I don't see any references to CUDA 12.

`ldconfig -p | grep cublas`:
```
        libcublasLt.so.11 (libc6,x86-64) => /usr/local/cuda-11.7/targets/x86_64-linux/lib/libcublasLt.so.11
        libcublasLt.so (libc6,x86-64) => /usr/local/cuda-11.7/targets/x86_64-linux/lib/libcublasLt.so
        libcublas.so.11 (libc6,x86-64) => /usr/local/cuda-11.7/targets/x86_64-linux/lib/libcublas.so.11
        libcublas.so (libc6,x86-64) => /usr/local/cuda-11.7/targets/x86_64-linux/lib/libcublas.so
```
`ldconfig -p | grep cudnn`:
```
        libcudnn_ops_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_train.so.8
        libcudnn_ops_train.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_train.so
        libcudnn_ops_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
        libcudnn_ops_infer.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_ops_infer.so
        libcudnn_cnn_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8
        libcudnn_cnn_train.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_train.so
        libcudnn_cnn_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8
        libcudnn_cnn_infer.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_cnn_infer.so
        libcudnn_adv_train.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_train.so.8
        libcudnn_adv_train.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_train.so
        libcudnn_adv_infer.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8
        libcudnn_adv_infer.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn_adv_infer.so
        libcudnn.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn.so.8
        libcudnn.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudnn.so
```
`ldd /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8`:
```
        linux-vdso.so.1 (0x00007ffdb1be2000)
        libcudnn_ops_infer.so.8 => /lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8 (0x00007f82fcee7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f82fcecb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f82fcec1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82fce9e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f82fce98000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f82fccb4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82fcb65000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f82fcb4a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82fc958000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f832821b000)
```

**Comment by guillaumekln** [comment] 2023-07-16 11:11
Can you also run `ldd` on `libcudnn_ops_infer.so.8`?

**Comment by luckymomohd** [comment] 2023-07-16 13:31
Running `ldd /lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8`:
```linux-vdso.so.1 (0x00007ffdf2480000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9d92074000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9d92051000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9d9204b000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9d91e69000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9d91d1a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9d91cfd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d91b0b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9d9791c000)```

**Comment by guillaumekln** [comment] 2023-07-17 08:07
I still think the issue is that the installed cuDNN 8 version is for CUDA 12 instead of CUDA 11. The library `libcublas.so.12` is not listed in the `ldd` output because cuDNN probably loads this library at runtime.

Please check how you installed cuDNN and make sure you install the version for CUDA 11.

**Comment by guillaumekln** [comment] 2023-07-18 07:44
Thanks for the confirmation.

@anderleich You should have the same issue so I'm closing this issue.

**Closed by guillaumekln** 2023-07-18 07:44 UTC
