### ISSUE TITLE
The Demo in the ReadMe doesn't work.

### ISSUE THREAD

**Issue by chengduoZH** [OpenNMT/CTranslate2#109] opened 2020-02-14 15:20 UTC
When I run the demo of ReadMe, I got an error:

```
Traceback (most recent call last):
  File "/root/miniconda3/bin/ct2-opennmt-py-converter", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/ctranslate2/bin/opennmt_py_converter.py", line 11, in main
    converters.OpenNMTPyConverter(args.model_path).convert_from_args(args)
  File "/root/miniconda3/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 39, in convert_from_args
    force=args.force)
  File "/root/miniconda3/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 53, in convert
    src_vocab, tgt_vocab = self._load(model_spec)
  File "/root/miniconda3/lib/python3.7/site-packages/ctranslate2/converters/opennmt_py.py", line 22, in _load
    checkpoint = torch.load(self._model_path, map_location="cpu")
  File "/root/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/root/miniconda3/lib/python3.7/site-packages/torchtext/vocab.py", line 119, in __setstate__
    if state['unk_index'] is None:
KeyError: 'unk_index'
```

The version of the torch is 1.4.0 and ctranslate2 is 1.5.1 on my development machine. And I add `'unk_index' not in state or` in "/root/miniconda3/lib/python3.7/site-packages/torchtext/vocab.py:199", this test is passed.

**Comment by guillaumekln** [comment] 2020-02-14 15:23
Does it work when you load and run the model with OpenNMT-py?

**Comment by guillaumekln** [comment] 2020-02-17 14:06
I can reproduce this, thanks for reporting. This looks like a regression in `torchtext` which was fixed for 0.5.0: https://github.com/pytorch/text/commit/7de812bef416120b7cacd6d0eeb47c6d60f3e434. The conversion runs without error when installing `torchtext==0.5.0`.

I'm just not sure why the same model is loading fine with OpenNMT-py. I will check further.

**Comment by guillaumekln** [comment] 2020-02-19 14:03
It seems there is nothing we can do in CTranslate2. Updating `torchtext` should be the fix for this error.

For reference, here is a related discussion on the forum: https://forum.opennmt.net/t/issue-loading-pretrained-models-for-machine-translation/2982

**Closed by guillaumekln** 2020-02-19 14:03 UTC
Labels: bug

**Comment by atikaakmal** [comment] 2020-10-22 12:56
Hi @guillaumekln 

I am trying to run this command (**ct2-opennmt-py-converter --model_path averaged-10-epoch.pt --model_spec TransformerBase --output_dir ende_ctranslate2**) on linux but **getting an error** that:

 **File "/workspace/env/lib/python3.6/site-packages/torchtext/vocab.py", line 119, in __setstate__
    if state['unk_index'] is None:
KeyError: 'unk_index**'

 Accoding to your comments above, I installed the **lateast version** of torchtext then **got this error:**

**opennmt-py 1.2.0 requires torchtext==0.4.0, but you'll have torchtext 0.5.0 which is incompatible.**

After that I again uninstalled 0.5.5 version and installed torchtext==0.4.0 version but the error was same **(File "/workspace/env/lib/python3.6/site-packages/torchtext/vocab.py", line 119, in __setstate__
    if state['unk_index'] is None:
KeyError: 'unk_index).**

Could you please give some advice how i can get rid from this error.

Thank you.

**Comment by francoishernandez** [comment] 2020-10-22 13:03
@atikaakmal it should be fine with torchtext==0.5.0 actually.
We should probably update the torchtext requirements in OpenNMT-py at some point.

**Comment by atikaakmal** [comment] 2020-10-23 08:42
Hi @francoishernandez 

Thanks for your reply. If I uodate torchtext, still the error is same. 
I am running on Docker and I am run this command 'docker pull opennmt/ctranslate2:latest-ubuntu18-cuda10.2' then getting an error message that ''bash: docker: command not found''. Eventhough the cuda version is same. 

Thank you.

**Comment by francoishernandez** [comment] 2020-10-23 09:21
> Thanks for your reply. If I uodate torchtext, still the error is same.

I just executed the exact same command with `torchtext==0.5.0`, `pytorch==1.6.0`, `OpenNMT-py==1.2.0`, `ctranslate2==1.14.0` on ubuntu 18.04. Are you sure you don't have any other version in your path? Maybe you could try from scratch with a virtualenv to isolate the issue.

> I am running on Docker and I am run this command 'docker pull opennmt/ctranslate2:latest-ubuntu18-cuda10.2' then getting an error message that ''bash: docker: command not found''. Eventhough the cuda version is same.

Not sure what you're saying here. Looks like there might be some issues with your docker install.

**Comment by atikaakmal** [comment] 2020-10-24 10:56
Hi @francoishernandez 

Thank for your reply. I am trying to run **pip install ctranslate2 on Windows 10 64 bit with GPU** but getting this following error: 

**ERROR: Could not find a version that satisfies the requirement ctranslate2 (from versions: none)
ERROR: No matching distribution found for ctranslate2**

Do you know how we can install on windows.

Thanks

**Comment by guillaumekln** [comment] 2020-10-24 11:09
Please read the documentation first. The README page indicates that the pre-built `ctranslate2` Python package requires a Linux system:

https://github.com/OpenNMT/CTranslate2#python-package

You can easily install a Linux system on Windows with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by atikaakmal** [comment] 2020-10-26 20:10
Hi @guillaumekln 

currently, I installed linux system in windows by following **WSL**.  After required installation, I make a script i.e test.py and wite this following code.

**import ctranslate2
import tokenize

translator = ctranslate2.Translator("ende_ctranslate2/")
results = translator.translate_batch(
    [tokenize(‘I am.’)],
    target_prefix=[tokenize("Ein Beispiel")],
    num_hypotheses=5,
    return_alternatives=True)
for hypothesis in results[0]:
    print(detokenize(hypothesis["tokens"]))** 

Unfortunately, I am getting this follwing error:

**[tokenize("I am i.")], 
TypeError: 'module' object is not collable**

**I am trying to run this script 'Alternatives at a position'**
https://github.com/OpenNMT/CTranslate2/blob/master/docs/decoding.md

Could please tell me where I am doing mistake or how I can run this script.

Thanks

**Comment by guillaumekln** [comment] 2020-10-26 20:20
Again, please read the documentation more carefully. The Decoding page explicitly says what the `tokenize` function should be.

I'm locking this conversation since the initial issue is resolved and it's going off-topic. Please post on the [forum](https://forum.opennmt.net/) if your need more help.
