### ISSUE TITLE
clang's aggressive optimization flags cause issues at runtime

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#556] opened 2021-09-09 07:23 UTC
After a month or so I switched to my Intel Mac to work on my code so I pulled the latest master branch of CTranslate2 and updated oneAPI to latest version. While the debug version of my application was working fine, the release mode couldn't translate anything. I verified that the issue was arising when calling `ctranslate2::TranslatorPool::translate_batch` -- the process would hang for many seconds, then it wouldn't return the translation.
When I removed the default optimization `-O3` everything returned to normal. The higher optimization flag I can add without issues is `-O1`. This is with Apple clang version 11.0.3. Any hints why this is happening?

**Comment by guillaumekln** [comment] 2021-09-09 07:57
Can you locate more precisely where it hangs in the code?

**Comment by panosk** [comment] 2021-09-09 08:17
I debugged with `-O3` and it hangs in `translator_pool.cc`, line 115:
```
template <typename T>
  std::vector<T> get_results_from_futures(std::vector<std::future<T>> futures) {
    std::vector<T> results;
    results.reserve(futures.size());
    for (auto& future : futures)
      results.emplace_back(future.get()); // <-- The delay occurs here
    return results;
  }
```

The `results` vector is not filled as it should. If more debugging is needed, let me know.

**Comment by guillaumekln** [comment] 2021-09-09 08:26
This code is waiting on the translator thread to return the result, but the actual issue is probably in the translator thread itself. Can you look inside the Translator?

**Comment by panosk** [comment] 2021-09-09 08:48
Well, starting from a breakpoint at the ctranslate2::TranslatorPool::translate_batch` call, I stepped through all the code, and the only bottleneck is there. This delay does not occur when I compile without `-O3`.

**Comment by panosk** [comment] 2021-09-09 09:05
Hm, please stand by, you are right, the bottleneck is elsewhere.

**Comment by panosk** [comment] 2021-09-09 10:44
Going a bit deeper, it seems the issue is in function `std::vector<GenerationResult<size_t>>
  BeamSearch::search`, starting at line 208, in `decoding.cc`, right before returning. It's a pretty long function with loops, so I'll debug more later if needed.

**Comment by guillaumekln** [comment] 2021-09-09 12:05
Note that the macOS CI job seems to run fine with the following:

* AppleClang 12.0.0.12000032
* Intel oneAPI 2021.3.0.3043

Maybe you can try updating the compiler?

**Comment by panosk** [comment] 2021-09-10 10:27
I will try that at first chance, thank you.

**Comment by guillaumekln** [comment] 2021-11-04 08:47
Did you get the chance to try a different compiler version?

**Comment by panosk** [comment] 2021-11-04 11:28
Few days ago I upgraded XCode so now I'm using AppleClang 13.0.0. The issue remains. The code compiles fine but with `-O3` the problem remains at runtime. I'll compile CTranslate2 separately and run some tests using the command line client and report back.

**Comment by guillaumekln** [comment] 2021-12-15 16:12
Did you happen to use INT8 models when facing this issue? I just fixed an [issue](https://github.com/OpenNMT/CTranslate2/commit/b0c1fbcfe6cebfbdcf468c505e2a601e86185dc3) that was found on Mac and I'm wondering if it can be related.

**Comment by guillaumekln** [comment] 2022-03-10 09:07
I'm closing this older issue since the published macOS Python wheel seems to work fine.

Feel free to reopen if the issue is still happening with the latest version and you can locate exactly where the execution is stuck.

**Closed by guillaumekln** 2022-03-10 09:07 UTC
